import { SiteHeader } from "@/components/site-header"
import { SiteFooter } from "@/components/site-footer"
import { BackButton } from "@/components/back-button"
import { ProtectedEmail } from "@/components/protected-email"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy - Statement to CSV",
  description: "Privacy Policy for Statement to CSV by Vergos Limited.",
}

export default function PrivacyPage() {
  return (
    <main className="min-h-screen">
      <SiteHeader />

      <section className="mx-auto max-w-3xl px-4 py-12 sm:px-6 md:py-20">
        <BackButton />
        <div className="prose prose-invert max-w-none space-y-6">
          <div>
            <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
              Privacy Policy
            </h1>
            <p className="mt-2 text-sm text-muted-foreground">
              Effective date: 2026-02-22
            </p>
          </div>

          <section className="space-y-4">
            <div>
              <h2 className="text-2xl font-semibold text-foreground">1. Introduction</h2>
              <p className="text-muted-foreground">
                Welcome to pdfbankstatementtocsv.
              </p>
              <p className="text-muted-foreground">
                pdfbankstatementtocsv ("us", "we", or "our") operates https://www.pdfbankstatementtocsv.co.za/ (hereinafter referred to as "Service"). Our Privacy Policy governs your visit to https://www.pdfbankstatementtocsv.co.za/, and explains how we collect, safeguard and disclose information that results from your use of our Service.
              </p>
              <p className="text-muted-foreground">
                We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
              </p>
              <p className="text-muted-foreground">
                Our Terms and Conditions ("Terms") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("agreement").
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">2. Definitions</h2>
              <ul className="list-inside space-y-2 text-muted-foreground">
                <li><strong>SERVICE</strong>: the https://www.pdfbankstatementtocsv.co.za/ website operated by pdfbankstatementtocsv.</li>
                <li><strong>PERSONAL DATA</strong>: data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
                <li><strong>USAGE DATA</strong>: data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>COOKIES</strong>: small files stored on your device (computer or mobile device).</li>
                <li><strong>DATA CONTROLLER</strong>: a natural or legal person who determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</li>
                <li><strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong>: any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</li>
                <li><strong>DATA SUBJECT</strong>: any living individual who is the subject of Personal Data.</li>
                <li><strong>THE USER</strong>: the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">3. Information Collection and Use</h2>
              <p className="text-muted-foreground">
                We collect several different types of information for various purposes to provide and improve our Service to you.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">4. Types of Data Collected</h2>
              
              <h3 className="text-xl font-semibold text-foreground mt-4">Personal Data</h3>
              <p className="text-muted-foreground">
                While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
              </p>
              <ul className="list-inside space-y-1 text-muted-foreground">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, Country, State, Province, ZIP/Postal code, City</li>
                <li>Cookies and Usage Data</li>
              </ul>
              <p className="text-muted-foreground mt-3">
                We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
              </p>

              <h3 className="text-xl font-semibold text-foreground mt-6">Usage Data</h3>
              <p className="text-muted-foreground">
                We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device ("Usage Data").
              </p>
              <p className="text-muted-foreground">
                This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>

              <h3 className="text-xl font-semibold text-foreground mt-6">Tracking Cookies Data</h3>
              <p className="text-muted-foreground">
                We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device.
              </p>
              <p className="text-muted-foreground mt-2">
                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
              </p>
              <p className="text-muted-foreground mt-2 font-semibold">Examples of Cookies we use:</p>
              <ul className="list-inside space-y-1 text-muted-foreground">
                <li>Session Cookies: We use Session Cookies to operate our Service.</li>
                <li>Preference Cookies: We use Preference Cookies to remember your preferences and various settings.</li>
                <li>Security Cookies: We use Security Cookies for security purposes.</li>
                <li>Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">5. Use of Data</h2>
              <p className="text-muted-foreground">
                pdfbankstatementtocsv uses the collected data for various purposes:
              </p>
              <ul className="list-inside space-y-1 text-muted-foreground">
                <li>To provide and maintain our Service</li>
                <li>To notify you about changes to our Service</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                <li>To provide customer support</li>
                <li>To gather analysis or valuable information so that we can improve our Service</li>
                <li>To monitor the usage of our Service</li>
                <li>To detect, prevent and address technical issues</li>
                <li>To fulfil any other purpose for which you provide it</li>
                <li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection</li>
                <li>To provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.</li>
                <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
                <li>In any other way we may describe when you provide the information</li>
                <li>For any other purpose with your consent</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">6. Retention of Data</h2>
              <p className="text-muted-foreground">
                We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
              </p>
              <p className="text-muted-foreground mt-2">
                We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">7. Transfer of Data</h2>
              <p className="text-muted-foreground">
                Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
              </p>
              <p className="text-muted-foreground mt-2">
                If you are located outside North America and choose to provide information to us, please note that we transfer the data, including Personal Data, to North America and process it there. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
              </p>
              <p className="text-muted-foreground mt-2">
                pdfbankstatementtocsv will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">8. Disclosure of Data</h2>
              <p className="text-muted-foreground">
                We may disclose personal information that we collect, or you provide:
              </p>
              <div className="space-y-4 mt-3">
                <div>
                  <h3 className="font-semibold text-foreground">Disclosure for Law Enforcement</h3>
                  <p className="text-muted-foreground">
                    Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
                  </p>
                </div>
                <div>
                  <h3 className="font-semibold text-foreground">Business Transaction</h3>
                  <p className="text-muted-foreground">
                    If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
                  </p>
                </div>
                <div>
                  <h3 className="font-semibold text-foreground">Other cases</h3>
                  <p className="text-muted-foreground">We may disclose your information also:</p>
                  <ul className="list-inside space-y-1 text-muted-foreground">
                    <li>To our subsidiaries and affiliates</li>
                    <li>To contractors, service providers, and other third parties we use to support our business</li>
                    <li>To fulfill the purpose for which you provide it</li>
                    <li>For the purpose of including your company's logo on our website</li>
                    <li>For any other purpose disclosed by us when you provide the information</li>
                    <li>With your consent in any other cases</li>
                    <li>If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others</li>
                  </ul>
                </div>
              </div>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">9. Security of Data</h2>
              <p className="text-muted-foreground">
                The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">10. Your Data Protection Rights Under GDPR</h2>
              <p className="text-muted-foreground">
                If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.
              </p>
              <p className="text-muted-foreground mt-2">
                We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data. If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at <ProtectedEmail email="vergos.ryan@gmail.com" />.
              </p>
              <p className="text-muted-foreground mt-2 font-semibold">In certain circumstances, you have the following data protection rights:</p>
              <ul className="list-inside space-y-1 text-muted-foreground">
                <li>The right to access, update or to delete the information we have on you</li>
                <li>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete</li>
                <li>The right to object. You have the right to object to our processing of your Personal Data</li>
                <li>The right of restriction. You have the right to request that we restrict the processing of your personal information</li>
                <li>The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format</li>
                <li>The right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information</li>
              </ul>
              <p className="text-muted-foreground mt-3">
                Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not be able to provide Service without some necessary data.
              </p>
              <p className="text-muted-foreground mt-2">
                You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">11. Your Data Protection Rights under CalOPPA</h2>
              <p className="text-muted-foreground">
                CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law's reach stretches well beyond California to require a person or company in the United States (and conceivably the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy.
              </p>
              <p className="text-muted-foreground mt-2 font-semibold">According to CalOPPA we agree to the following:</p>
              <ul className="list-inside space-y-1 text-muted-foreground">
                <li>Users can visit our site anonymously</li>
                <li>Our Privacy Policy link includes the word "Privacy", and can easily be found on the home page of our website</li>
                <li>Users will be notified of any privacy policy changes on our Privacy Policy Page</li>
                <li>Users are able to change their personal information by emailing us at <ProtectedEmail email="vergos.ryan@gmail.com" /></li>
              </ul>
              <div className="mt-4 p-4 bg-secondary/50 rounded-lg">
                <p className="font-semibold text-foreground mb-2">Our Policy on "Do Not Track" Signals:</p>
                <p className="text-muted-foreground">
                  We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked. You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
                </p>
              </div>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">12. Your Data Protection Rights under CCPA</h2>
              <p className="text-muted-foreground">
                If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
              </p>
              <div className="space-y-4 mt-3">
                <div>
                  <p className="font-semibold text-foreground">What personal information we have about you</p>
                  <p className="text-muted-foreground mt-1">If you make this request, we will return to you:</p>
                  <ul className="list-inside space-y-1 text-muted-foreground ml-2">
                    <li>The categories of personal information we have collected about you</li>
                    <li>The categories of sources from which we collect your personal information</li>
                    <li>The business or commercial purpose for collecting or selling your personal information</li>
                    <li>The categories of third parties with whom we share personal information</li>
                    <li>The specific pieces of personal information we have collected about you</li>
                    <li>A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact</li>
                    <li>A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with</li>
                  </ul>
                  <p className="text-muted-foreground mt-2 text-sm">
                    Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.
                  </p>
                </div>
                <div>
                  <p className="font-semibold text-foreground">To delete your personal information</p>
                  <p className="text-muted-foreground mt-1">
                    If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.
                  </p>
                </div>
                <div>
                  <p className="font-semibold text-foreground">To stop selling your personal information</p>
                  <p className="text-muted-foreground mt-1">
                    We don't sell or rent your personal information to any third parties for any purpose. We do not sell your personal information for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without monetary consideration may be considered a "sale" under California law. You are the only owner of your Personal Data and can request disclosure or deletion at any time.
                  </p>
                </div>
              </div>
              <p className="text-muted-foreground mt-4">
                If you submit a request to stop selling your personal information, we will stop making such transfers. Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances will we discriminate against you for exercising your rights.
              </p>
              <p className="text-muted-foreground mt-3">
                To exercise your California data protection rights described above, please send your request(s) by email: <ProtectedEmail email="vergos.ryan@gmail.com" />.
              </p>
              <p className="text-muted-foreground mt-2 text-sm">
                Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">13. Service Providers</h2>
              <p className="text-muted-foreground">
                We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
              </p>
              <p className="text-muted-foreground mt-2">
                These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">14. Analytics</h2>
              <p className="text-muted-foreground">
                We may use third-party Service Providers to monitor and analyze the use of our Service.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">15. CI/CD Tools</h2>
              <p className="text-muted-foreground">
                We may use third-party Service Providers to automate the development process of our Service.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">16. Behavioral Remarketing</h2>
              <p className="text-muted-foreground">
                We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">17. Payments</h2>
              <p className="text-muted-foreground">
                We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).
              </p>
              <p className="text-muted-foreground mt-2">
                We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">18. Links to Other Sites</h2>
              <p className="text-muted-foreground">
                Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
              </p>
              <p className="text-muted-foreground mt-2">
                We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">19. Children's Privacy</h2>
              <p className="text-muted-foreground">
                Our Services are not intended for use by children under the age of 18 ("Child" or "Children").
              </p>
              <p className="text-muted-foreground mt-2">
                We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">20. Changes to This Privacy Policy</h2>
              <p className="text-muted-foreground">
                We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
              </p>
              <p className="text-muted-foreground mt-2">
                We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update "effective date" at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-semibold text-foreground">21. Contact Us</h2>
              <p className="text-muted-foreground">
                If you have any questions about this Privacy Policy, please contact us by email: <ProtectedEmail email="vergos.ryan@gmail.com" />.
              </p>
            </div>
          </section>
        </div>
      </section>

      <SiteFooter />
    </main>
  )
}
